---
# This installs the Couchbase Server software only and does not
# actually initialize a cluster, see cluster_init.yml for that

- hosts: couchbase
  sudo: True
  roles:
    - common
    - couchbase
  tasks:
    - name: Couchbase Server Service
      service: name=couchbase-server state=started enabled=yes

    - name: Wait for Admin
      wait_for: port=8091 delay=20

    - name: Wait for EPMD
      wait_for: port=4369 delay=20
