---
- name: Deploy HDP 2.2
  hosts: all
  sudo: true
  tasks:
  - name: Install epel repo
    yum: name=epel-release state=present

  - name: Install packages
    yum: name={{item}} state=present
    with_items:
      - java
      - openssl-1.0.1e
      - wget
      - ntp
      - python-pip
      - libselinux-python

  - name: Install Python requests module
    pip: name={{item}}
    with_items:
      - httplib2
      - requests

  - selinux: state=disabled

  - name: Disable SELinux
    command: setenforce 0

  - service: name=iptables state=stopped enabled=no

  - service: name=ntpd state=started enabled=yes

  - sysctl: name=vm.swappiness value=1 state=present ignoreerrors=yes

  - name: Disable THP (1)
    command: echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag

  - name: Disable THP (2)
    command: echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled

  - name: Disable THP (3)
    lineinfile: dest=/etc/rc.local
                line='echo never > /sys/kernel/mm/redhat_transparent_hugepage/defrag'
                state=present

  - name: Disable THP (4)
    lineinfile: dest=/etc/rc.local
                line='echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled'
                state=present

  - name: Update /etc/security/limits.conf
    lineinfile: dest=/etc/security/limits.conf
                insertbefore='# End of file'
                line='* - nofile 65536'
                state=present

  - user: name=vagrant generate_ssh_key=yes

  - name: Copy public key
    command: cat /home/vagrant/.ssh/id_rsa.pub
    register: id_rsa_pub

  - authorized_key: user=vagrant key='{{ id_rsa_pub.stdout }}'

  - name: Download ambari.repo
    get_url: url=http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.7.0/ambari.repo dest=/etc/yum.repos.d/ambari.repo mode=0644

  - name: Install Ambari Server
    yum: name=ambari-server state=present
    register: installed_ambari_server

  - name: Download Java for Ambari
    get_url: url=http://public-repo-1.hortonworks.com/ARTIFACTS/{{item}} dest=/vagrant/deps/{{item}}
    with_items:
      - jdk-7u67-linux-x64.tar.gz
      - UnlimitedJCEPolicyJDK7.zip
    when: installed_ambari_server|changed

  - name: Copy Java to Ambari resources
    command: cp /vagrant/deps/{{item}} /var/lib/ambari-server/resources/{{item}} creates=/var/lib/ambari-server/resources/{{item}}
    with_items:
      - jdk-7u67-linux-x64.tar.gz
      - UnlimitedJCEPolicyJDK7.zip

  - name: Setup ambari-server
    shell: ambari-server setup -s
    when: installed_ambari_server|changed

  - name: Ensure Ambari server running
    service: name=ambari-server state=restarted enabled=yes
    when: installed_ambari_server|changed

  - wait_for: port=8080 delay=3
    when: installed_ambari_server|changed

  - name: Ambari agent bootstrap 
    sudo: no
    command: python /vagrant/bootstrap_ambari_agent.py

  - name: Add cluster blueprint to Ambari
    sudo: no
    command: python /vagrant/add_cluster_blueprint.py

  # Wait for up to 45 min for the cluster to come up
  - name: Install cluster via Ambari blueprint
    sudo: no
    command: python /vagrant/install_cluster.py
    async: 2700
    poll: 10
