#!/bin/sh
#
# kibana4          Start/Stop Kibana4.
#
### BEGIN INIT INFO
# Provides:          kibana4
# Required-Start:    $network $remote_fs $named
# Required-Stop:     $network $remote_fs $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts kibana4
# Description:       Starts kibana4
### END INIT INFO

#configure this with wherever you unpacked kibana:
KIBANA_BIN=/usr/share/kibana-4.0.0-linux-x64/bin

PID_FILE=/var/run/kibana.pid
LOG_FILE=/var/log/kibana.log
exec=$KIBANA_BIN/kibanad
RETVAL=0
prog="kibana"
lockfile=/var/lock/subsys/$prog

# Source function library.
. /etc/rc.d/init.d/functions

[ $UID -eq 0 ] && [ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
    if [ $UID -ne 0 ] ; then
        echo "User has insufficient privilege."
        exit 4
    fi
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    daemon --pidfile $PID_FILE $exec $PID_FILE $LOG_FILE
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
}

stop() {
    if [ $UID -ne 0 ] ; then
        echo "User has insufficient privilege."
        exit 4
    fi
    echo -n $"Stopping $prog: "
    killproc -p $PID_FILE $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
}

restart() {
    rh_status_q && stop
    start
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $PID_FILE $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?

