---
- name: Install and launch Node app
  hosts: all
  sudo: yes
  tasks:
  - name: Install dependencies
    yum: name={{ item }} state=latest
    with_items:
    - libselinux-python
    - git

  - name: Setup yum repo
    shell: curl -sL https://rpm.nodesource.com/setup | bash -

  - name: Install node rpm
    yum: name=nodejs state=latest

  - name: copy app
    copy: src=../elasticsearch-twitter-webapp dest=/opt/

  - name: install app
    npm: path=/opt/elasticsearch-twitter-webapp

  - name: install forever module
    npm: name=forever global=yes state=latest

  - name: start the app forever
    shell: forever start -c "npm start --unsafe-perm" /opt/elasticsearch-twitter-webapp/
