---
elasticsearch_version: 1.4.4
elasticsearch_package: elasticsearch-{{ elasticsearch_version }}.noarch.rpm
elasticsearch_url: https://download.elasticsearch.org/elasticsearch/elasticsearch/{{ elasticsearch_package }}
