---
- hosts: node
  sudo: True
  gather_facts: False
  vars:
    nodejs_app_name: elasticsearch-twitter-webapp
    app_port: 8000
  tasks:
    - name: stop all forever apps
      command: forever stopall

    - name: remove app
      file: path=/opt/{{ nodejs_app_name }} state=absent

    - name: copy app
      copy: src=../../../{{ nodejs_app_name }} dest=/opt/ owner=root group=root

    - name: start the app forever
      command: forever start -c "npm start --unsafe-perm" /opt/{{ nodejs_app_name }}/

    - name: wait for elasticsearch-twitter-webapp to start
      wait_for: port={{ app_port }} delay=5
